[versions]
agp = "9.4.0"
appcompat = "1.8.0"
constraintlayout = "2.2.2"
lifecycle = "2.11.0"
material = "1.14.0"
activity = "1.13.0"

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycle" }
lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata", version.ref = "lifecycle" }
material = { module = "com.google.android.material:material", version.ref = "material" }
activity = { module = "androidx.activity:activity", version.ref = "activity" }
