[versions]
agp = "9.4.0"
androidxAppcompat = "1.8.0"
androidxPreference = "1.2.1"
androidxFragment = "1.9.0"
material = "1.14.0"
androidxActivity = "1.13.0"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppcompat" }
androidx-preference = { module = "androidx.preference:preference", version.ref = "androidxPreference" }
androidx-fragment = { module = "androidx.fragment:fragment", version.ref = "androidxFragment" }
material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "androidxActivity" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
